#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import signal
from taemin import bot

def reload_conf(signum, frame):
    bot.reload_conf()

if __name__ == "__main__":
    signal.signal(signal.SIGHUP, reload_conf)
    bot = bot.Taemin()
    bot.start()

