#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import errno
import signal
import select
import sys

import irc.client

from taemin import bot

def reload_conf(signum, frame):
    bot.reload_conf()

if __name__ == "__main__":
    signal.signal(signal.SIGHUP, reload_conf)
    bot = bot.Taemin(*sys.argv[1:])

    try:
        bot.start()
    except select.error as err:
        if err.args[0] != errno.EINTR:
            raise

    while True:
        try:
            irc.client.SimpleIRCClient.start(bot)
        except select.error as err:
            if err.args[0] != errno.EINTR:
                raise

