#!/usr/bin/env python
# -*- coding: utf-8 -*-

import errno
import signal
import select
import irc.client
from taemin import bot

def reload_conf(signum, frame):
    bot.reload_conf()

if __name__ == "__main__":
    signal.signal(signal.SIGHUP, reload_conf)
    bot = bot.Taemin()

    try:
        bot.start()
    except select.error as (code, msg):
        if code != errno.EINTR:
            raise

    while(True):
        try:
            irc.client.SimpleIRCClient.start(bot)
        except select.error as (code, msg):
            if code != errno.EINTR:
                raise

